wheel_sets = {'Alpha [LEA]',
              'Beta [LEB]',
              'Unlimited Edition [2ED]',
              'Arabian Nights [ARN]',
              'Antiquities [ATQ]',
              'Revised Edition [3ED]',
              'Legends [LEG]',
              'The Dark [DRK]',
              'Fallen Empires [FEM]',
              'Fourth Edition [4ED]',
              'Ice Age [ICE]',
              'Chronicles [CHR]',
              'Homelands [HML]',
              'Alliances [ALL]',
              'Mirage [MIR]',
              'Visions [VIS]',
              'Fifth Edition [5ED]',
              'Portal [POR]',
              'Weatherlight [WTH]',
              'Tempest [TMP]',
              'Stronghold [STH]',
              'Exodus [EXO]',
              'Portal Second Age [P02]',
              'Urza\'s Saga [USG]',
              'Urza\'s Legacy [ULG]',
              'Sixth Edition [6ED]',
              'Portal Three Kingdoms [PTK]',
              'Urza\'s Destiny [UDS]',
              'Mercadian Masques [MMQ]',
              'Battle Royale [BRB]',
              'Nemesis [NEM]',
              'Prophecy [PCY]',
              'Invasion [IN]',
              'Beatdown [BTD]',
              'Planeshift [PLS]',
              'Seventh Edition [7ED]',
              'Apocalypse [APC]',
              'Odyssey [ODY]',
              'Torment [TOR]',
              'Judgement [JUD]',
              'Onslaught [ONS]',
              'Legions [LGN]',
              'Scourge [SCG]',
              'Eighth Edition [8ED]',
              'Mirrodin [MRD]',
              'Darksteel [DST]',
              'Fifth Dawn [5DN]',
              'Champions of Kamigawa [CHK]',
              'Betrayers of Kamigawa [BOK]',
              'Saviors of Kamigawa [SOK]',
              'Ninth Edition [9ED]',
              'Ravnica: City of Guilds [RAV]',
              'Guildpact [GPT]',
              'Dissension [DIS]',
              'Coldsnap [CSP]',
              'Time Spiral [TSP]',
              'Planar Chaos [PLC]',
              'Future Sight [FUT]',
              'Tenth Edition [10E]',
              'Lorwyn [LRW]',
              'Morningtide [MOR]',
              'Shadowmoor [SHM]',
              'Eventide [EVE]',
              'Shards of Alara [ALA]',
              'Conflux [CON]',
              'Alara Reborn [ARB]',
              'Magic 2010 [M10]',
              'Planechase [HOP]',
              'Zendikar [ZEN]',
              'Worldwake [WWK]',
              'Rise of the Eldrazi [ROE]',
              'Archenemy [ARC]',
              'Magic 2011 [M11]',
              'Scars of Mirrodin [SOM]',
              'Mirrodin Besieged [MBS]',
              'New Phyrexia [NPH]',
              'Commander [CMD]',
              'Magic 2012 [M12]',
              'Innistrad [ISD]',
              'Dark Ascension [DKA]',
              'Avacyn Restored [AVR]',
              'Magic 2013 [M13]',
              'Return to Ravnica [RTR]',
              'Commander\'s Arsenal [CM1]',
              'Gatecrash [GTC]',
              'Dragon\'s Maze [DGM]',
              'Magic 2014 [M14]',
              'Theros [THS]',
              'Commander 2013 [C13]',
              'Born of the Gods [BNG]',
              'Journey to Nyx [JOU]',
              'Conspiracy [CNS]',
              'Magic 2015 [M15]',
              'Khans of Tarkir [KTK]',
              'Commander 2014 [C14]',
              'Fate Reforged [FRF]',
              'Dragons of Tarkir [DTK]',
              'Magic Origins [ORI]',
              'Battle for Zendikar [BFZ]',
              'Commander 2015 [C15]',
              'Oath of the Gatewatch [OGW]',
              'Shadows over Innistrad [SOI]',
              'Eldritch Moon [EMN]',
              'Kaladesh [KLD]',
              'Kaladesh Inventions [MPS]',
              'Commander 2016 [C16]',
              'Aether Revolt [AER]',
              'Amonkhet [AKH]',
              'Archenemy: Nicol Bolas [E01]',
              'Hour of Devestaton [HOU]',
              'Commander 2017 [C17]',
              'Ixalan [XLN]',
              'Rivals of Ixalan [RIX]',
              'Dominaria [DOM]',
              'Battlebond [BBD]',
              'Core Set 2019 [M19]',
              'Commander 2018 [C18]',
              'Guilds of Ravnica [GRN]',
              'Ravnica Allegiance [RNA]',
              'War of the Spark [WAR]',
              'Modern Horizons [MH1]',
              'Core Set 2020 [M20]',
              'Commander 2019 [C19]',
              'Throne of Eldraine [ELD]'}
